### ISSUE TITLE
Mulltiple accounts?

### ISSUE THREAD

**Issue by DerLomo** [jlobos/instagram-web-api#233]
How can I make the script to run different accounts?
The cookie.json is giving me problems, may i create a list of users and passwords and change the way cookies are stored to save each cookies by the name of the users?

**Comment by MonsieurBibo** [comment]
To make it work, you would have to modify the code so that each cookie is associated with an ID. This can be done with named directories or just files like `ID-cookie.json`. Then you just need to retrieve data from the wanted cookie. However, I think IG might be able to spot it because of your IP / robotic behavior, so be careful.
